# Numpy

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [2]:
import numpy as np
fname = 'minutes_n_ingredients.csv'
a = np.loadtxt(fname, skiprows = 1, dtype='int', unpack = True, delimiter = ',')

print(a.T[0:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [3]:
print("Минимум:", np.min(a.T[:,0]), np.min(a.T[:,1]), np.min(a.T[:,2]))
print("Максимум:", np.max(a.T[:,0]), np.max(a.T[:,1]), np.max(a.T[:,2]))
print("Среднее:", np.mean(a.T[:,0]), np.mean(a.T[:,1]), np.mean(a.T[:,2]))
print("Медиана:", np.median(a.T[:,0]), np.median(a.T[:,1]), np.median(a.T[:,2]))

Минимум: 38 0 1
Максимум: 537671 2147483647 39
Среднее: 222064.32391 21601.00169 9.05528
Медиана: 207193.5 40.0 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [4]:
q = np.quantile(a.T[:, 1], q=0.75) 
a.T[:, 1] = a.T[:, 1].clip(max=q)
print(a.T)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [5]:
print("Количество нулей:", a.T[:,1].size - np.count_nonzero(a.T[:,1]))
a.T[:,1] = np.where(a.T[:,1]==0, 1, a.T[:,1])
print(a.T)

Количество нулей: 479
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [6]:
print("Уникальных наборов:", len(np.unique(a.T, axis=0)))

Уникальных наборов: 100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [7]:
print("Всего различных количеств ингридиентов:", len(np.unique(a.T[:,2], axis=0)))
un = np.unique(a.T[:,2], axis=0)
print("Эти ингридиенты:", un)

Всего различных количеств ингридиентов: 37
Эти ингридиенты: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [8]:
a = a.T[np.where(a.T[:,2] <= 5)]
print(a)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [9]:
b = (a[:,1] / a[:,2])
print(b)
print(max(b))

[ 3.          1.66666667  1.5        ... 12.          3.75
  1.25      ]
65.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [10]:
a_sorted_desc = a.T[a.T[:, 1]. argsort ()[::-1]]
c = a_sorted_desc[: 100]
print(np.mean(c[:,2]))

8544.333333333334


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [11]:
number_of_rows = a.shape[0]
random_indices = np.random.choice(number_of_rows, size=10, replace=False)
row = a[random_indices, :]
print(row)

[[ 59684     37      5]
 [428216      2      3]
 [435430     30      5]
 [238038     65      5]
 [440398     25      5]
 [209142      5      5]
 [ 86618     20      3]
 [360541     65      5]
 [130241     20      4]
 [193089     65      5]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [12]:
e = a[np.where(a[:,2] < np.mean(a[:,2]))]
kolvo_e, columns = e.shape
kolvo_at, columns_at = a.shape
percent = (kolvo_e / kolvo_at) * 100
print(percent, '%')

54.15942532730854 %


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

In [13]:
d = a[np.where((a[:,2] <= 5) & (a[:,1] <= 20))] 
kolvo_d, columns = d.shape
kolvo_a, columns1 = a.shape
percent = (kolvo_d / kolvo_a) * 100
print(percent, '%')

55.335418839068474 %


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.